### ISSUE TITLE
hyperlink hover fails to display URL preview at bottom of window

### ISSUE THREAD

**Issue by edmoz** [bwinton/VerticalTabs#75]
1. hover over hyperlink

actual: url preview doesn't display at bottom left of window

expected: it should, like when tab center isn't installed

**Comment by wresuolc** [comment]
screenshot:

![tc-hover](https://cloud.githubusercontent.com/assets/16946141/14861727/512d0d68-0c63-11e6-857d-21f571985690.png)

**Comment by bwinton** [comment]
I wonder if this is also related to #74…

**Comment by pmclanahan** [comment]
> I wonder if this is also related to #74…

Could be. I can see that the preview is being shown, but a little less than have of it is visible above the bottom of the window and resizing doesn't help.

**Comment by bwinton** [comment]
I _think_ this was also fixed by e3bcf62fe36e61a9e0cd4e3f59a1f8bc6a034a6f…
(Confirmed fixed by @pmclanahan over irc.)

**Comment by wresuolc** [comment]
I'm using Tab Center 1.13 and this is the same (see my screenshot above).  Was this fix included in the 1.13 release?

**Comment by bwinton** [comment]
Hmm.  It should have been.  Can you disable and re-enable, to make sure the latest code is getting loaded, and let me know which version of Firefox and OS you're running on?

**Comment by wresuolc** [comment]
Enable/Disable works great now! :) 

Still seeing the problem.  It's Ubuntu with Nightly from April 28.  Ubuntu has a dark theme by default, which is why the bar is black.

If I don't use Tab Center, the bar is black letters on grey background.  It seems like Tab Center is asking the OS to draw it instead of something built in to Fx so it's showing up with the OS theme background but not the font color.  </guessing>

**Comment by edmoz** [comment]
I'm still seeing the problem, I'm on 1.13 (may 3) mac nightly.  I've restarted a couple times too.

**Comment by bwinton** [comment]
@edmoz So, I can't seem to reproduce it…  Do you have other add-ons installed?  Can you reproduce it in a new profile?  Can you give me a page and link that definitely doesn't work so I can make sure I'm testing against the same stuff you are?

<img width="628" alt="screenshot 2016-05-03 12 07 51" src="https://cloud.githubusercontent.com/assets/159571/14989821/aefcc096-1127-11e6-8baa-dd7f4d5e1d5f.png">

Thanks!

**Comment by edmoz** [comment]
@bwinton you're right - I can't repro on a clean profile.  It has to be a addon collision.  I'll turn off some suspect addons

**Comment by bwinton** [comment]
Yay!  \o/  :wink:

**Comment by wresuolc** [comment]
I can still reproduce on a brand new profile.

**Comment by bwinton** [comment]
Yep, that's a different bug, @wresuolc (but I'm working on it now).
Actually, did you want to [file a new issue](https://github.com/bwinton/VerticalTabs/issues/new) for that?

**Comment by wresuolc** [comment]
Sure thing.  Lucky #100
